HIP-630 using gipc for multiprcessing in rescan
================================================================================

Host Power Tools / HIP-630
volume unmap - Caught an unhandled exception

Type:              Bug                               Status:        Resolved                   Assignee: Guy Rozendorn
Priority:          Major                             Resolution:    Fixed                      Reporter: Shlomi Penner
Affects Version/s: 0.27                              Fix Version/s: 0.28
Components: volume provissioning                                                               Created: 2013-07-02 16:28
Labels:                                                                                        Updated: 2013-07-10 09:28

Issue Links:

Sub-Tasks:

Description:
when unmapping mounted volume, infinihost returns:
{noformat}
> infinihost volume unmap /mnt/shlomip-ubuntu.infinidat.com-vol-20131302-1413 --yes
Caught an unhandled exception
Log file is located at /var/log/infinihost.2013-07-02.16-01.debug.log
{noformat}

  instead of "cannot unmount filesystem {fsName} device is busy"

Comments:
Guy Rozendorn added a comment - 2013-07-10 09:24
This is what you're going to see:
{noformat}
[root@host-ci33 ~]# infinihost volume unmap dm-1 --yes
ERROR: Cannot unmount filesystem /dev/mapper/mpathcp1, device /mnt/host-ci33.infinidat.com-vol-20131710-0917 is busy
{noformat}